export const ADD_EVENTS = 'ADD_EVENTS';
export const DELETE_EVENTS = 'DELETE_EVENTS';
export const EDIT_EVENTS = 'EDIT_EVENTS';
export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_EVENTS_BY_ID = 'FETCH_EVENTS_BY_ID';
export const FETCH_EVENTS_BY_OWNER = 'FETCH_EVENTS_BY_OWNER';

export const FETCH_VOLUNTEERS_BY_EMAIL = 'FETCH_VOLUNTEERS_BY_EMAIL';
export const ADD_VOLUNTEERS = 'ADD_VLOUNTEERS';
export const FETCH_VOLUNTEERS = 'FETCH_VOLUNTEERS';

export const ADD_SITE_VOLUNTEER = 'ADD_SITE_VOLUNTEER';
export const FETCH_VOLUNTEERS_BY_SITE = 'FETCH_VOLUNTEERS_BY_SITE';

export const LOG_IN = 'LOG_IN';
export const REGISTER = 'REGISTER';
export const INVALID = 'INVALID';


export const DOWNLOAD_EVENTS_BY_ACCOUNT = 'DOWNLOAD_EVENTS_BY_ACCOUNT';

export const FETCH_ACCOUNTS_BY_ID = 'FETCH_ACCOUNTS_BY_ID';

